CREATE TABLE Books(
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  Name Varchar(50) UNIQUE,
  AuthorID INT REFERENCES Authors(id) 
);

CREATE TABLE Authors(
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  Name Varchar(50) NOT NULL
);

CREATE TABLE Customers(
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  Name Varchar(50) NOT NULL,
  email Varchar(50) NOT NULL
);

CREATE TABLE Rents(
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  BookID INTEGER REFERENCES Books(id),
  CustomerID INTEGER REFERENCES Customers(id),
  State Varchar(15) NOT NULL
);