"""add image and description to products

Revision ID: 6461302df5ed
Revises: 655791ab8582
Create Date: 2026-06-03 19:02:20.741429

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6461302df5ed'
down_revision: Union[str, Sequence[str], None] = '655791ab8582'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('image', sa.String(length=500), nullable=True), schema='pets_eccomerce')
    op.add_column('products', sa.Column('description', sa.Text(), nullable=True), schema='pets_eccomerce')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'description', schema='pets_eccomerce')
    op.drop_column('products', 'image', schema='pets_eccomerce')
    # ### end Alembic commands ###
